blank_issues_enabled: false
contact_links:
  - name: GitHub Copilot Tutorial
    url: https://aka.ms/github-copilot-hol
    about: Visit the ultimate GitHub Copilot tutorial on MOAW
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Ask questions and discuss with the community
  - name: Security Vulnerability
    url: https://github.com/heristop/gh-copilot-demo/security/advisories/new
    about: Report a security vulnerability privately
